Repository sighupio/furyctl, pull requests merged in 2023-01, with the labels that each got.

#131 Feature/first wave adjustments
  .drone.yml
  Makefile
  cmd/create/cluster.go
  cmd/delete/cluster.go
  internal/apis/kfd/v1alpha2/eks/create/distribution.go
  internal/apis/kfd/v1alpha2/eks/create/infrastructure.go
  internal/apis/kfd/v1alpha2/eks/create/kubernetes.go
  internal/apis/kfd/v1alpha2/eks/creator.go
  internal/apis/kfd/v1alpha2/eks/delete/distribution.go
  internal/apis/kfd/v1alpha2/eks/delete/infrastructure.go
  internal/apis/kfd/v1alpha2/eks/delete/kubernetes.go
  internal/apis/kfd/v1alpha2/eks/deleter.go
  internal/cluster/creator.go
  internal/cluster/deleter.go
  internal/tool/kubectl/runner.go
  test/e2e/furyctl_test.go
Labels: enhancement

#146 feat: renamed bucket to bucketName
  go.mod
  go.sum
  test/data/e2e/create/cluster/data/furyctl-defaults.yaml
  test/data/e2e/create/cluster/data/furyctl.yaml
  test/data/e2e/create/cluster/data/schemas/ekscluster-kfd-v1alpha2.json
  test/data/e2e/download/dependencies/v1.24.1/distro/furyctl-defaults.yaml
  test/data/e2e/download/dependencies/v1.24.1/distro/schemas/ekscluster-kfd-v1alpha2.json
  test/data/e2e/dump/template/complex-dry-run/furyctl-defaults.yaml
  test/data/e2e/dump/template/complex-dry-run/furyctl.yaml
  test/data/e2e/dump/template/complex/furyctl-defaults.yaml
  test/data/e2e/validate/config/correct/furyctl-defaults.yaml
  test/data/e2e/validate/config/correct/furyctl.yaml
  test/data/e2e/validate/config/correct/schemas/ekscluster-kfd-v1alpha2.json
  test/data/e2e/validate/config/wrong/furyctl-defaults.yaml
  test/data/e2e/validate/config/wrong/schemas/ekscluster-kfd-v1alpha2.json
  test/data/expensive/common/data/furyctl-defaults.yaml
  test/data/expensive/common/data/schemas/ekscluster-kfd-v1alpha2.json
  test/data/expensive/common/data/templates/distribution/manifests/dr/resources/velero-backupstoragelocation.yml.tpl
  test/data/expensive/common/data/templates/distribution/terraform/velero.tf.tpl
  test/data/integration/v1.24.1/distro/furyctl-defaults.yaml
  test/data/integration/v1.24.1/distro/schemas/ekscluster-kfd-v1alpha2.json
Labels: enhancement

#147 feat: removed furyctl binary version check
  cmd/create.go
  cmd/create/cluster.go
  cmd/create/config.go
  cmd/delete.go
  cmd/delete/cluster.go
  cmd/download.go
  cmd/download/dependencies.go
  cmd/root.go
  cmd/validate.go
  cmd/validate/config.go
  cmd/validate/dependencies.go
  internal/distribution/download.go
  internal/distribution/download_test.go
Labels: enhancement

#149 feat: handle unsupported phases
  cmd/create/cluster.go
  cmd/delete/cluster.go
  internal/apis/kfd/v1alpha2/eks/create/distribution.go
  internal/apis/kfd/v1alpha2/eks/create/infrastructure.go
  internal/apis/kfd/v1alpha2/eks/create/kubernetes.go
  internal/apis/kfd/v1alpha2/eks/delete/distribution.go
  internal/apis/kfd/v1alpha2/eks/delete/infrastructure.go
  internal/apis/kfd/v1alpha2/eks/delete/kubernetes.go
  internal/cluster/phase.go
  test/e2e/furyctl_test.go
  test/expensive/furyctl_test.go
Labels: bug

#128 Handling private or non exist modules
  internal/dependencies/download.go
Labels: enhancement

#154 feat: added dry run to cluster delete
  cmd/create/cluster.go
  cmd/delete/cluster.go
  internal/apis/kfd/v1alpha2/eks/delete/distribution.go
  internal/apis/kfd/v1alpha2/eks/delete/infrastructure.go
  internal/apis/kfd/v1alpha2/eks/delete/kubernetes.go
  internal/tool/kubectl/runner.go
  internal/tool/terraform/runner.go
Labels: enhancement

#156 chore: check github token whitespaces, improve logrus format
  cmd/download.go
  cmd/vendor.go
Labels: bug, enhancement

#158 chore: remove logrus timestamp format
  main.go
Labels: enhancement

#157 feat: added dry-run logic in phase distribution to create cluster cmd
  internal/apis/kfd/v1alpha2/eks/create/distribution.go
  internal/tool/kubectl/runner.go
Labels: enhancement

#161 chore: rename create cluster flag's functions
  cmd/create/cluster.go
Labels: enhancement

#170 Feat: Warn the user about connectivity when running kubernetes phase
  internal/apis/kfd/v1alpha2/eks/creator.go
Labels: enhancement

#173 Feat: UX improvement about unsupported KFD version
  internal/distribution/download.go
  internal/x/net/hashicorp.go
  test/e2e/furyctl_test.go
Labels: enhancement

#174 Feat: support file:// and env:// for every phase in furyctl.yaml
  go.mod
  go.sum
  internal/apis/kfd/v1alpha2/eks/create/infrastructure.go
  internal/apis/kfd/v1alpha2/eks/create/kubernetes.go
  internal/template/mapper/mapper.go
  internal/template/mapper/mapper_test.go
  internal/x/bytes/buffer.go
  internal/x/bytes/buffer_test.go
Labels: enhancement

#180 Fix: auto-complete not working due to logrus
  cmd/completion.go
  cmd/root.go
  main.go
Labels: bug

#171 Feat: clean up vendor folder before dl and remove .git subfolder after dl
  internal/dependencies/download.go
Labels: enhancement

#176 Feat: add depth=1 to go-getter urls
  cmd/create/cluster.go
  cmd/create/config.go
  cmd/delete/cluster.go
  cmd/download/dependencies.go
  cmd/validate/config.go
  cmd/validate/dependencies.go
  internal/dependencies/download.go
  internal/distribution/download.go
Labels: enhancement

#172 Feat: check cluster connectivity in distribution phase
  internal/apis/kfd/v1alpha2/eks/create/distribution.go
  internal/apis/kfd/v1alpha2/eks/creator.go
  internal/apis/kfd/v1alpha2/eks/delete/distribution.go
  internal/dependencies/tools/kubectl_test.go
  internal/tool/kubectl/runner.go
  internal/tool/kubectl/runner_test.go
  internal/tool/runner.go
Labels: enhancement

#182 Feat: switched to output json in command kubectl version
  cmd/validate/dependencies.go
  internal/dependencies/tools/kubectl.go
  internal/dependencies/tools/test_data/kubectl/1.21.1/kubectl
  internal/dependencies/tools/test_data/kubectl/1.22.0/kubectl
  internal/dependencies/tools/tool_test.go
  internal/tool/kubectl/runner.go
  test/data/e2e/validate/dependencies/correct/kubectl/1.24.9/kubectl
  test/data/e2e/validate/dependencies/wrong/kubectl/1.24.9/kubectl
Labels: enhancement

#189 Feat: added support to LogRetentionDays and NodePoolsLaunchKind
  go.mod
  go.sum
  internal/apis/kfd/v1alpha2/eks/create/kubernetes.go
  test/data/e2e/create/cluster/data/furyctl.yaml
  test/data/e2e/create/cluster/data/schemas/ekscluster-kfd-v1alpha2.json
  test/data/e2e/create/config/default/data/expected-furyctl.yaml
  test/data/e2e/create/config/distro/templates/config/ekscluster-kfd-v1alpha2.yaml.tpl
  test/data/e2e/download/dependencies/v1.24.1/furyctl.yaml
  test/data/e2e/dump/template/complex-dry-run/furyctl.yaml
  test/data/e2e/dump/template/complex/furyctl.yaml
  test/data/e2e/validate/config/correct/furyctl.yaml
  test/data/e2e/validate/config/correct/schemas/ekscluster-kfd-v1alpha2.json
  test/data/e2e/validate/config/nodistro/furyctl.yaml
  test/data/e2e/validate/config/wrong/furyctl.yaml
  test/data/e2e/validate/config/wrong/schemas/ekscluster-kfd-v1alpha2.json
  test/data/e2e/validate/dependencies/correct/furyctl.yaml
  test/data/e2e/validate/dependencies/missing/furyctl.yaml
  test/data/e2e/validate/dependencies/wrong/furyctl.yaml
  test/data/expensive/create-complete/data/furyctl.yaml
  test/data/expensive/create-skip-infra/data/furyctl.yaml
  test/data/expensive/create-skip-kube/data/furyctl.yaml
  test/data/integration/v1.24.1/furyctl.yaml
Labels: enhancement

#192 Feat: support no-tty in external commands
  cmd/create/cluster.go
  cmd/delete/cluster.go
  cmd/root.go
  internal/tool/terraform/runner.go
  internal/x/exec/cmd.go
  internal/x/logrus/config.go
Labels: bug

#160 Feat: update README for furyctl-ng
  .goreleaser.yml
  README.md
  cmd/create.go
  cmd/create/cluster.go
  cmd/create/config.go
  cmd/delete.go
  cmd/delete/cluster.go
  cmd/download.go
  cmd/download/dependencies.go
  cmd/dump.go
  cmd/root.go
  cmd/validate.go
  cmd/validate/config.go
  cmd/validate/dependencies.go
  internal/apis/kfd/v1alpha2/eks/creator.go
  internal/apis/kfd/v1alpha2/eks/deleter.go
  internal/cluster/deleter.go
  test/e2e/furyctl_test.go
Labels: enhancement
