Repository sighupio/furyctl, pull requests merged in 2023-04, with the labels that each got.

#340 fix: converted file and env from object to string in template engine
  internal/template/generator_test.go
  internal/template/mapper/mapper.go
  internal/template/mapper/mapper_test.go
  test/data/e2e/dump/template/complex-dry-run/furyctl.yaml
  test/data/e2e/dump/template/complex/furyctl.yaml
  test/data/e2e/validate/config/nodistro/furyctl.yaml
  test/data/e2e/validate/config/wrong/furyctl.yaml
  test/data/e2e/validate/dependencies/correct/furyctl.yaml
  test/data/e2e/validate/dependencies/missing/furyctl.yaml
  test/data/e2e/validate/dependencies/wrong/furyctl.yaml
Labels: bug

#327 feat: added coredns patch on phase kubernetes
  configs/provisioners/cluster/eks/coredns.tf.tpl
  configs/provisioners/cluster/eks/variables.tf
  internal/apis/kfd/v1alpha2/eks/create/kubernetes.go
  internal/distribution/iac.go
Labels: bug, enhancement

#347 feat: initial update Vpc.Vpn -> Infrastructure.Vpn
  go.mod
  go.sum
  internal/apis/kfd/v1alpha2/eks/create/infrastructure.go
  internal/apis/kfd/v1alpha2/eks/create/kubernetes.go
  internal/apis/kfd/v1alpha2/eks/creator.go
  internal/apis/kfd/v1alpha2/eks/delete/infrastructure.go
  internal/apis/kfd/v1alpha2/eks/delete/kubernetes.go
  internal/apis/kfd/v1alpha2/eks/deleter.go
  internal/apis/kfd/v1alpha2/eks/tool.go
  internal/apis/kfd/v1alpha2/eks/vpn.go
  internal/dependencies/tools/test_data/furyctl.yaml
  test/data/e2e/create/cluster/data/furyctl.yaml
  test/data/e2e/create/cluster/data/schemas/public/ekscluster-kfd-v1alpha2.json
  test/data/e2e/create/config/default/data/expected-furyctl.yaml
  test/data/e2e/create/config/distro/templates/config/ekscluster-kfd-v1alpha2.yaml.tpl
  test/data/e2e/download/dependencies/v1.24.1/furyctl.yaml
  test/data/e2e/dump/template/complex-dry-run/furyctl.yaml
  test/data/e2e/dump/template/complex/furyctl.yaml
  test/data/e2e/validate/config/correct/furyctl.yaml
  test/data/e2e/validate/config/correct/schemas/public/ekscluster-kfd-v1alpha2.json
  test/data/e2e/validate/config/nodistro/furyctl.yaml
  test/data/e2e/validate/config/wrong/furyctl.yaml
  test/data/e2e/validate/config/wrong/schemas/public/ekscluster-kfd-v1alpha2.json
  test/data/e2e/validate/dependencies/correct/furyctl.yaml
  test/data/e2e/validate/dependencies/missing/furyctl.yaml
  test/data/e2e/validate/dependencies/wrong/furyctl.yaml
  test/data/expensive/create-complete/data/furyctl.yaml
  test/data/expensive/create-skip-infra/data/furyctl.yaml
  test/data/expensive/create-skip-kube/data/furyctl.yaml
  test/data/integration/v1.24.1/furyctl.yaml
Labels: enhancement

#354 feature/delete loki deployments
  internal/apis/kfd/v1alpha2/eks/delete/distribution.go
  internal/kubernetes/client.go
  internal/kubernetes/client_test.go
  internal/tool/kubectl/runner.go
Labels: bug

#358 feat: removed openvpn requirement when not using --vpn-auto-connect
  cmd/create/cluster.go
  cmd/delete/cluster.go
  cmd/validate/dependencies.go
  go.mod
  go.sum
  internal/apis/kfd/v1alpha2/eks/create/infrastructure.go
  internal/apis/kfd/v1alpha2/eks/tool.go
  internal/apis/tool.go
  internal/dependencies/tools/validator.go
  internal/dependencies/tools/validator_test.go
  internal/dependencies/validate.go
Labels: enhancement

#363 fix: missing region from vpc connectivity check
  internal/apis/kfd/v1alpha2/eks/create/kubernetes.go
  internal/apis/kfd/v1alpha2/eks/delete/kubernetes.go
Labels: bug

#367 chore: UX improvements
  cmd/create/cluster.go
  cmd/delete/cluster.go
  cmd/download.go
  cmd/download/dependencies.go
  cmd/validate.go
  cmd/validate/config.go
  cmd/validate/dependencies.go
  cmd/version.go
  internal/apis/kfd/v1alpha2/eks/vpn.go
Labels: enhancement

#368 feat: added git tool check
  cmd/create/cluster.go
  cmd/create/config.go
  cmd/delete/cluster.go
  cmd/download/dependencies.go
  cmd/dump/template.go
  cmd/validate/config.go
  cmd/validate/dependencies.go
  internal/dependencies/tools/git.go
  internal/dependencies/tools/git_test.go
  internal/dependencies/tools/tool.go
  internal/dependencies/tools/tool_test.go
  internal/dependencies/tools/validator.go
  internal/dependencies/tools/validator_test.go
  internal/dependencies/validate.go
  internal/tool/git/runner.go
  internal/tool/git/runner_test.go
  internal/tool/runner.go
Labels: enhancement
